name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: get nightly toolchain
        id: toolchain
        uses: dtolnay/rust-toolchain@nightly
      - name: save target directory
        id: target
        uses: actions/cache@v4
        with:
          path: target
          key: ${{runner.os}}-${{steps.toolchain.outputs.cachekey}}
      - name: Build
        run: cargo +nightly build --verbose
      - name: Run tests
        run: cargo +nightly test --verbose
